apiVersion: v1
kind: ConfigMap
metadata:
  name: config1
data:
  MYSQL_USER: mahendra
  MYSQL_DATABASE: sampledb
  MYSQL_PASSWORD: pass$12345
  MYSQL_ROOT_PASSWORD: pass$12345

---

apiVersion: v1
kind: Pod
metadata: 
  name: pod-2
spec:
  containers:
  - name: db
    image: mysql:8.0
    resources:  
      limits: 
        cpu: 500m
        memory: 512Mi
    envFrom:
      - configMapRef:
          name: config1