apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: set2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
        - name: web
          image: mahendrshinde/myweb:1
          resources:
            requests:
              cpu: 100m
              memory: 32Mi
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: set2
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50